version: '2'

services:
    postgres:
      image: postgres:latest
      container_name: test_database_10
      volumes:
        - pgdata_10:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=test
        - POSTGRES_USER=test
        - POSTGRES_DB=test

    redis:
      image: redis
      container_name: test_redis
      ports:
        - "6379:6379"
            
volumes:
    pgdata_10:
